### PR TITLE
Install package from repository / Make Systemd Great Again

### LINKED ISSUE #7: Parent directory /usr/lib/systemd/system does not exist
## Affects
* default-ubuntu-xenial64
* default-debian-jessie64

## Output
```
         * template[/usr/lib/systemd/system/varnish.service] action create
           * Parent directory /usr/lib/systemd/system does not exist.
           ================================================================================
           Error executing action `create` on resource 'template[/usr/lib/systemd/system/varnish.service]'
           ================================================================================

           Chef::Exceptions::EnclosingDirectoryDoesNotExist
           ------------------------------------------------
           Parent directory /usr/lib/systemd/system does not exist.

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cop_varnish/recipes/configure.rb

            49: template '/usr/lib/systemd/system/varnish.service' do
            50:     cookbook 'cop_varnish'
            51:     source   'varnish.service.erb'
            52:     group    'root'
            53:     owner    'root'
            54:     mode     0644
            55:     backup   5
            56:     action   :create
            57:     only_if  'ps -p 1 -o comm= | grep systemd'
            58:     notifies :run, 'execute[reload systemctl]', :immediately
            59:     notifies :restart, 'service[varnish]', :delayed
            60: end
            61:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cop_varnish/recipes/configure.rb:49:in `from_file'

           template("/usr/lib/systemd/system/varnish.service") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             source "varnish.service.erb"
             cookbook "cop_varnish"
             declared_type :template
             cookbook_name "cop_varnish"
             recipe_name "configure"
             owner "root"
             group "root"
             mode 420
             backup 5
             path "/usr/lib/systemd/system/varnish.service"
             only_if "ps -p 1 -o comm= | grep systemd"
           end

           Platform:
           ---------
           x86_64-linux

         * service[varnish] action restart

           ================================================================================
           Error executing action `restart` on resource 'service[varnish]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '6'
           ---- Begin output of /bin/systemctl --system restart varnish ----
           STDOUT:
           STDERR: Failed to restart varnish.service: Unit varnish.service failed to load: No such file or directory.
           ---- End output of /bin/systemctl --system restart varnish ----
           Ran /bin/systemctl --system restart varnish returned 6

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cop_varnish/recipes/configure.rb

            76: service 'varnish' do
            77:     action [:enable, :start]
            78: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cop_varnish/recipes/configure.rb:76:in `from_file'

           service("varnish") do
             action [:enable, :start]
             supports {:restart=>nil, :reload=>nil, :status=>nil}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "varnish"
             pattern "varnish"
             declared_type :service
             cookbook_name "cop_varnish"
             recipe_name "configure"
           end

           Platform:
           ---------
           x86_64-linux
```

### LINKED ISSUE #12: Install won't complete correctly if prior `varnishd` exists
Install recipe checks for presence of `varnishd` in a not_if, this can cause an unexpected outcome where the specified version tarball downloads, but is never installed.

### LINKED ISSUE #15: Brittle test case for full version of package
Check for major version only

### PR DESCRIPTION
**Pull request by jerrywardlow**
Big changes in this one, looking for lots of feedback.

* Moves to package based installation from Packagecloud (the officially supported Varnish repository) as http://repo.varnish-cache.org/source/ is due for deprecation 31 August 2017
* Changes configuration templates to account for systemd and legacy (Ubuntu Trusty 14.04) Varnish service configurations. This is inline with the official documentation on configuring the service. https://varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html
* Drops CentOS 6 and Debian Wheezy from Kitchen test suite, adds Debian Stretch.
* Updates tests to check for installed package and major version. Checking major version alone is in line with the end users ability to select a specific version from the repository, i.e., the user can specify only a major version for installation.
* Include attribute `node['varnish']['cache_purge_pattern']` to allow setting the behavior when a `PURGE` request is received.

Test suite now passes on all platforms, fixes #7 fixes #12  fixes #15

### CODE REVIEW

File: recipes/dependencies.rb [hunk 1]
```diff
@@ -9,3 +9,37 @@
...
+        action  :nothing
+    end
+
+when 'rhel'
+
+    yum_repository 'varnish' do
+        description "Varnish Repository - Packagecloud"
+        baseurl "https://packagecloud.io/varnishcache/varnish#{node['varnish']['version']}/el/#{node['platform_version'].to_i}/$basearch/"
+        enabled true
+        gpgcheck false
```
Comment (jerrywardlow) [inline recipes/dependencies.rb]: Yes, it fails for unknown reasons. Setting `gpgcheck` to false follows the repo setup outlined in the documentation.
https://packagecloud.io/varnishcache/varnish5/install#manual
